# This workflow will do a clean install of dependencies and run webpack build.

name: Run Webpack Build

on: 
  push:
      branches-ignore:
        - main 
  pull_request:
    

env:
  BUNDLE_ANALYZER_TOKEN: ${{ secrets.BUNDLE_ANALYZER_TOKEN }}
  CI: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - run: npm ci
    - run: npm run build:ci --if-present