# This workflow will do a clean install of dependencies and run webpack build.

name: Run Webpack Build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
      env:
        BUNDLE_ANALYZER_TOKEN: ${{ secrets.BUNDLE_ANALYZER_TOKEN }}
        CI: true
    - run: npm ci
    - run: npm run build:prod --if-present